### ISSUE TITLE
需要增加的功能建议

### ISSUE THREAD

**Issue by adinghub** [spritecn/leanoteJava#3]
回收站，让被删除笔记有机会恢复
数据库可以方便地备份或导出 JSON，每篇笔记的每个历史版本也可以导出
新增一个简陋的 Reminder(提醒事项) 功能

**Comment by spritecn** [comment]
Reminder 

> 回收站，让被删除笔记有机会恢复
> 数据库可以方便地备份或导出 JSON，每篇笔记的每个历史版本也可以导出
> 新增一个简陋的 Reminder(提醒事项) 功能

**Comment by spritecn** [comment]
> 回收站，让被删除笔记有机会恢复
> 数据库可以方便地备份或导出 JSON，每篇笔记的每个历史版本也可以导出
> 新增一个简陋的 Reminder(提醒事项) 功能


1 回收站是默认功能（即2.6版本废纸篓功能) 默认支持
2 当前没有前端 ，暂未考虑做界面，考虑后期做界面支持
3 此功能需要桌面端新增功能，也需要前端 支持

**Comment by spritecn** [comment]
看来没前端 啥都干不成
